name: Publish npm package to GitHub Packages

on:
  push:
    branches: [main]
    # We'll need to make this resuable so we can use it in other packages
    paths:
      - 'packages/auth/**'

jobs:
  publish:
    runs-on: [self-hosted, linux, X64]
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Set up Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: npm ci

      - name: Create changeset
        run: npx changeset

      - name: Test package
        run: npx nx run auth:test

      - name: Build package
        run: npx nx run auth:build

      - name: Generate release notes
        id: release
        run: |
          npx changeset version \
            --generate-release-notes \
            --output-format json
          echo "::set-output name=notes::$(cat .changeset-release.json)"

      - name: Publish package to GitHub Packages
        run: |
          npx changeset version && \
          npm publish packages/auth
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create GitHub release
        uses: actions/create-release@v1
        if: ${{ steps.release.outputs.notes }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.release.outputs.notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-changelog:
    needs: publish
    runs-on: [self-hosted, linux, X64]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install changesets
        run: npm install -g @changesets/cli

      - name: Install conventional changelog
        run: npm install -g conventional-changelog-cli

      - name: Generate changelog
        run: |
          changesets-to-changelog -i ./CHANGELOG.md -s @changesets/cli -r
          git add ./CHANGELOG.md
          git commit -m "Update auth changelog"
          git push
